apps/goods/urls.py
from django.urls import path
from . import views


app_name='goods'
urlpatterns=[
    path('',views.index,name='index'),
    path('type/<int:pk>/',views.goods_list,name='type_list'),
    path('goods/<int:pk>/',views.goods,name='goods'),
    path('search',views.search,name='search')
]

apps/user/urls.py
from django.urls import path
from . import views
app_name='user'
urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('forget_password/',views.forget,name='forget_pwd'),
    path('change_password/<uid>/',views.change_pwd,name='pwd_change'),
    path('user_center/',views.user_center,name='user_center'),
    path('address/',views.address,name='address'),
    path('order/',views.user_order,name='user_order'),
    path('add_address/',views.add_address,name='add_addr')
]

ttx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('apps.user.urls',namespace='user')),
    path('cart/',include('apps.cart.urls',namespace='cart')),
    path('order/',include('apps.order.urls',namespace='order')),
    path('',include('apps.goods.urls',namespace='goods')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/order/models.py
from django.db import models
from db import BaseMode
from apps.user.models import User
from apps.goods.models import Goods
# Create your models here.

class OrderInfo(BaseMode):
    pay_ways=(
        (1,'货到付款'),
        (2,'支付宝'),
        (3,'微信付款'),
        (4,'银联付款')
    )
    pay_status=(
        (1,'待支付'),
        (2,'待评价'),
        (3,'待发货'),
        (4,'待收货'),
        (5,'已完成'),
    )
    id=models.AutoField('订单id',primary_key=True)
    user=models.ForeignKey(User,verbose_name='用户',on_delete=models.CASCADE)
    pay_way=models.SmallIntegerField('支付方式',default=2,choices=pay_ways)
    count=models.IntegerField('商品总数')
    total=models.DecimalField('总价',decimal_places=2,max_digits=10)
    status=models.SmallIntegerField('状态',default=1,choices=pay_status)
    order_no=models.CharField('支付编号',max_length=100)

    class Meta:
        db_table='df_order_info'
        verbose_name = verbose_name_plural ='订单表'


class OrderGoods(BaseMode):
    order=models.ForeignKey(OrderInfo,on_delete=models.CASCADE,verbose_name='订单')
    sku=models.ForeignKey(Goods,on_delete=models.CASCADE,verbose_name='商品')
    count=models.IntegerField('商品数目')
    comment=models.TextField('评论')
    @property
    def price(self):
        return self.sku.price * self.count

    class Meta:
        db_table='df_order_goods'
        verbose_name = verbose_name_plural ='订单商品表'

apps/user/models.py
from django.db import models
from db import BaseMode
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser,BaseMode):

    def __str__(self):
        return self.username

    class Meta:
        db_table='df_user'
        verbose_name=verbose_name_plural='用户表'

class Address(BaseMode):
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='所属用户')
    receiver=models.CharField('收件人',max_length=100)
    addr=models.CharField('地址',max_length=100)
    postcode=models.CharField('邮编',max_length=100)
    phone=models.CharField('号码',max_length=11)
    is_default=models.BooleanField(default=True,verbose_name='是否默认地址')

    def __str__(self):
        return self.receiver

    class Meta:
        db_table='df_address'
        verbose_name = verbose_name_plural ='地址表'

apps/user/views.py
from django.contrib.auth import authenticate,logout, login as login_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password,check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from apps.goods.views import client
from apps.goods.models import Goods


from .models import User
import re
# Create your views here.

"""
实现用户注册登入功能模块
"""

#用户注册视图函数
def register(request):
    if request.method=='POST':
        name=request.POST.get('user_name')
        pwd=request.POST.get('pwd')
        cpwd=request.POST.get('cpwd')
        email=request.POST.get('email')
        allow=request.POST.get('allow')     #选中为on
        if not all((name,pwd,cpwd,email,allow)):
            return render(request,'register.html',{'errmsg':'信息不完整'})
        if pwd!=cpwd:
            return render(request,'register.html',{'errmsg':'密码不正确'})
        if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
            return render(request,'register.html',{'errmsg':'邮箱格式不正确'})
        if allow != 'on':
            return render(request,'register.html',{'errmsg':'请同意协议'})
        try:
            User.objects.create(username=name,password=make_password(pwd),email=email)

        except Exception:
            return render(request, 'register.html', {'errmsg': '改用户名以被注册'})
        else:
            return redirect(reverse('user:login'))

    return render(request,'register.html')

#用户登入视图函数
def login(request):
    if request.method=='POST':
        name=request.POST.get('username')
        pwd=request.POST.get('pwd')
        next=request.POST.get('next')
        choice =request.POST.get('remember')
        if all((name,pwd)):
            user=authenticate(request,username=name,password=pwd)
            if user:
                res=redirect(next)
                if choice=='on':
                    #登入页面是否记住用户，设置永久不过期
                    res.set_cookie('username',name,max_age=10)
                else:
                    res.delete_cookie('username')
                login_user(request,user)    #设置用户session信息，可用request.user调用
                return res
            else:
                return render(request, 'login.html', {'erro':'用户名和密码不正确'})
        else:
            return render(request, 'login.html', {'erro':'请输入用户名和密码'})

    else:
        next=request.GET.get('next')
        if not next:
            next=reverse('goods:index')
        username=request.COOKIES.get('username',"")
        checked=''
        if username:
            checked='checked'
        return render(request,'login.html',{'username':username,'checked':checked,'next':next})

#用户退出登入视图函数
def logout_user(request):
    logout(request)
    return redirect(reverse('goods:index'))

# 忘记密码发送邮件视图函数
def forget(request):
    if request.method=='POST':
        email=request.POST.get('email')
        if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
            return render(request,'forget_password.html',{'err':'请输入正确邮箱'})
        user=User.objects.filter(email=email).first()
        if user:
            uid=urlsafe_base64_encode(force_bytes(user.id))
            send_mail('修改密码', render_to_string('pwd_change.html',{'uid':uid}),'111@111.com',[email])
            return render(request,'forget_password.html')
        return render(request,'forget_password.html',{'err':'此邮箱未注册账号'})



    return render(request,'forget_password.html')

#点击邮件链接修改密码视图函数
def change_pwd(request,uid):
    id=int(urlsafe_base64_decode(uid).decode())
    if request.method=='POST':
        name=request.POST.get('name')
        new=request.POST.get('new')
        user = User.objects.get(id=id)
        if name==user.username:
            user.password=make_password(new)
            user.save()
            return redirect(reverse('user:login'))
        return render(request, 'change.html',{'err':'用户名错误'})
    return render(request,'change.html')


def user_center(request):
    goods=client.smembers(request.user.username)
    li=[]
    for good in list(goods):
        li.append(Goods.objects.get(pk=int(good)))
    li=li[::-1][:4]
    return render(request,'user_center.html',{'page':'user','lit':li})

def address(request):
    addr = request.user.address_set.all()
    default_addr=None
    if addr:
        default_addr=request.user.address_set.get(is_default=True)
    if request.method=='POST':
        addrs=request.POST.get('address')
        addr.update(is_default=False)
        addressed=request.user.address_set.filter(addr=addrs).first()
        addressed.is_default=True
        addressed.save()

    return render(request,'address.html',{'page':'addr','addr':addr,'default_addr':default_addr})


def add_address(request):
    if request.method=='POST':
        addrs=request.user.address_set.all()
        receiver=request.POST.get('receiver')
        address=request.POST.get('addr')
        code=request.POST.get('zip_code')
        phone=request.POST.get('phone')
        if not addrs:
            request.user.address_set.create(user=request.user,receiver=receiver,addr=address,postcode=code,phone=phone)
        else:
            request.user.address_set.create(user=request.user, receiver=receiver, addr=address, postcode=code, phone=phone,is_default=False)
    return redirect(reverse('user:address'))

def user_order(request):
    user=request.user
    orders=user.orderinfo_set.all().order_by('id')
    paginator=Paginator(orders,1)
    page=int(request.GET.get('page',1))
    if page > paginator.num_pages:
        page = paginator.num_pages
    elif page < 1:
        page = 1
    page_obj = paginator.page(page)
    return render(request,'user_order.html',{'page':'order','li':orders,'obj':page_obj,'paginator':paginator})

apps/user/templates/address.html
{% extends 'user_base_info.html' %}
{% block content %}

		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
                    <form method="post">
                    {% csrf_token %}
                        <label>当前地址</label>
                        {% if addr %}

                                <select name="address">
                                {% for d in addr %}
                                    <option value="{{ d.addr }}" {% if d.addr == default_addr.addr %}selected{% endif %}>{{ d.addr }}</option>
                                {% endfor %}
                                </select>
                            <button>确定更改</button>

                        {% else %}
                            <p>没有默认地址</p>
                        {% endif %}

                    </form>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:add_addr' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" id="receiver" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" id="addr" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" id="zip_code" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" id="phone" name="phone">
						</div>
                        <input type="hidden" id="addr_id" name="addr_id" value="0">
                        <input type="hidden" id="type" name="type" value="change">
						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
{% endblock %}

apps/user/templates/change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<h1>修改密码</h1>
<form method="post">
    <p style="color: red">{{ err }}</p>
    {% csrf_token %}
    <label>用户名</label>
    <input type="text" name="name"><br>
    <label>新密码:</label>
    <input type="text" name="new"><br>
    <button>修改</button>
</form>
</body>
</html>

apps/user/templates/forget_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发送邮件</title>
</head>
<body>
<h1>修改密码</h1>
<p>提示：输入邮箱，并点击发送邮件，请您注意查收邮件信息，点击邮件内链接修改密码</p>
<form method="post">
    {% csrf_token %}
    <p style="color: red">{{ err }}</p>
    <label>邮箱:</label>
    <input type="text" name="email" placeholder="请输入注册的邮箱">
    <button>发送邮件</button>
</form>

</body>
</html>

apps/user/templates/login.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">


</head>
<body>

	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href={% url 'user:register' %}>立即注册</a>
				</div>
                <div><p style="color: red;text-align: center">{{ erro }}</p></div>
				<div class="form_input">

					<form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ username }}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="{% url 'user:forget_pwd' %}">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>

				</div>
			</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>




</body>
</html>

apps/user/templates/pwd_change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<h1>请点击下面链接修改密码</h1>
<p><a href="http://127.0.0.1:8000{% url 'user:pwd_change' uid %}">修改密码</a></p>

</body>
</html>

apps/user/templates/register.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">


	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>

</head>
<body>

	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
                <p style="font-size: 10px;color: red;text-align: center">{{ errmsg }}</p>
				<form method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>

			</div>

		</div>

	</div>


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>




</body>
</html>

apps/user/templates/user_base_info.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>天天生鲜-用户中心</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

				<div class="login_btn fl">
					欢迎您：<em>{{ request.user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center' %}">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order/1">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
    <div class="main_con clearfix"  style="background: url('{% static 'images/left_bg.jpg' %}') repeat-y">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:user_order' %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'addr' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block content %}
        {% endblock %}
    </div>


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{% block js %}

{% endblock %}
</body>
</html>

apps/user/templates/user_center.html
{% extends 'user_base_info.html' %}
{% block content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.user.username }}</li>

                                <li><span>联系方式：</span>{{ request.user.address_set.first.phone }}</li>
							    <li><span>联系地址：</span>{{ request.user.address_set.first.addr }}</li>

						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for x in lit %}

				        <li>
                            <a href="{% url 'goods:goods' x.id %}"><img src="{{ x.img.url }}"></a>
                            <h4><a href="{% url 'goods:goods' x.id %}">{{ x.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ x.price }}</span>
                                <span class="unit">{{ x.price }}/500g</span>
                            </div>
                        </li>
                        {% endfor %}
			        </ul>
		        </div>
		</div>

{% endblock %}

apps/user/templates/user_order.html
{% extends 'user_base_info.html' %}
{% block content %}
<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
    {% for order in obj %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create }}</li>
					<li class="col02" style="width: 30%">订单号:{{ order.order_no }}</li>
					<li class="col02 stress">{{ order.get_pay_way_display }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for good in order.ordergoods_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="{{ good.sku.img.url }}"></li>
									<li class="col02">{{ good.sku.price }}<em>{{ good.sku.price }}元/500g</em></li>
									<li class="col03">{{ good.count }}</li>
									<li class="col04">{{ good.price }}元</li>
								</ul>{% endfor %}

							</td>
							<td width="15%">{{ order.total }}元</td>
							<td width="15%">待支付</td>
							<td width="15%"><a href="javascript:;" order_id="{{ order.id }}" status="{{ order.status }}" class="oper_btn">{{ order.get_status_display }}</a></td>
						</tr>
					</tbody>
				</table>
    {% endfor %}
				<div class="pagenation">

                            {% if obj.has_previous %}
                            <a href="{% url 'user:user_order' %}?page={{ obj.previous_page_number }}" class="active">&lt</a>
                {% endif %}
                            {% for x in paginator %}
					        <a href="{% url 'user:user_order' %}?page={{ x.number }}" {% if x.number != obj.number %}class="active"{% endif %}>{{ x.number }}</a>

                            {% endfor %}
                {% if obj.has_next %}
                    <a href="{% url 'user:user_order' %}?page={{ obj.next_page_number }}" class="active">&gt</a>
                {% endif %}

				</div>
		</div>


{% endblock %}
{% block js %}

    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>

    $('.oper_btn').click(function () {
       // 获取status
       status = $(this).attr('status')
       // 获取订单id
       order_id = $(this).attr('order_id')
       if (status == 1){
           // 进行支付
           csrf = $('input[name="csrfmiddlewaretoken"]').val()
           // 组织参数
           params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}
           // 发起ajax post请求，访问/order/pay, 传递参数:order_id
           $.post('/order/pay', params, function (data) {
               if (data.res == 3){
                   // 引导用户到支付页面
                   window.open(data.pay_url)
                   // 浏览器访问/order/check, 获取支付交易的结果
                   // ajax post 传递参数:order_id
                   {#$.post('/order/check', params, function (data){#}
                   {#    if (data.res == 3){#}
                   {#        alert('支付成功')#}
                   {#        // 刷新页面#}
                   {#        location.reload()#}
                   {#    }#}
                   {#    else{#}
                   {#        alert(data.errmsg)#}
                   {#    }#}
                   {#})#}
               }
               else{
                   alert(data.errmsg)
               }
           })
       }
       else if (status == 4){
           // 其他情况
           // 跳转到评价页面
           location.href = '/order/comment/'+order_id
       }
    })
    </script>
{% endblock %}