apps/goods/urls.py
from django.urls import path
from . import views


app_name='goods'
urlpatterns=[
    path('',views.index,name='index'),
    path('type/<int:pk>/',views.goods_list,name='type_list'),
    path('goods/<int:pk>/',views.goods,name='goods'),
    path('search',views.search,name='search')
]

ttx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('apps.user.urls',namespace='user')),
    path('cart/',include('apps.cart.urls',namespace='cart')),
    path('order/',include('apps.order.urls',namespace='order')),
    path('',include('apps.goods.urls',namespace='goods')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/goods/models.py
from django.db import models
from db import BaseMode

# Create your models here.
class GoodsType(BaseMode):
    type=models.CharField('类别',max_length=100)
    image=models.ImageField('商品类别图片',upload_to='type')
    logo=models.CharField(max_length=10)

    def __str__(self):
        return self.type

    class Meta:
        db_table='df_goods_type'
        verbose_name = verbose_name_plural ='商品类别表'


class Goods(BaseMode):
    name=models.CharField(max_length=100)
    type=models.ForeignKey(GoodsType,on_delete=models.CASCADE)
    img=models.ImageField(upload_to='fruit')
    desc=models.TextField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    class Meta:
        db_table='df_goods'
        verbose_name = verbose_name_plural ='商品表'


class Banner(BaseMode):
    img=models.ImageField(upload_to='banner')
    index=models.PositiveIntegerField()

    class Meta:
        db_table='df_index_goodsbanner'
        verbose_name = verbose_name_plural ='轮播图'


class Index_activity(BaseMode):
    name=models.CharField('活动名称',max_length=100)
    url=models.URLField('活动链接')
    images=models.ImageField('活动图片',upload_to='banner')
    index=models.SmallIntegerField(default=0,verbose_name='展示顺序')

    class Meta:
        db_table='df_index_activity'
        verbose_name = verbose_name_plural ='活动表'

apps/goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Banner,Index_activity,GoodsType,Goods
# Create your views here.
from apps.cart.views import Cart
from django_redis import get_redis_connection


client=get_redis_connection('default')
def index(request):
    banner=Banner.objects.order_by('index')
    active=Index_activity.objects.order_by('index')
    Type=GoodsType.objects.all()
    count=len(Cart(request).cart)
    return render(request,'index.html',locals())

def goods_list(request,pk):
    Type=GoodsType.objects.all()
    kinds=GoodsType.objects.get(pk=pk)
    goods_list=kinds.goods_set.all()
    qs=request.GET.get('order_by','id')
    goods=kinds.goods_set.all().order_by(qs)
    paginator=Paginator(goods,4)
    page=int(request.GET.get('page','1'))
    if page>paginator.num_pages:
        page=paginator.num_pages
    elif page<1:
        page=1
    page_obj=paginator.page(page)
    count = len(Cart(request).cart)
    return render(request,'type_list.html',locals())

def goods(request,pk):
    good=Goods.objects.get(pk=pk)
    Type = GoodsType.objects.all()
    goods=Goods.objects.filter(type=good.type).all()[:2]
    count = len(Cart(request).cart)
    if request.user.is_authenticated:
        #添加用户浏览记录
        client.sadd(request.user.username,good.id)
    return render(request,'good.html',locals())

def search(request):
    Type = GoodsType.objects.all()
    fruit=request.GET.get('fruit')
    goods=Goods.objects.filter(name__contains=fruit).all()
    paginator = Paginator(goods, 6)
    page = int(request.GET.get('page', '1'))
    if page > paginator.num_pages:
        page = paginator.num_pages
    elif page < 1:
        page = 1
    page_obj = paginator.page(page)
    return render(request,'search.html',locals())

apps/goods/templates/good.html
{% extends 'base.html' %}
{% block title %}
<title>天天生鲜-商品详情</title>
{% endblock %}
{% block nav %}
<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                   {% for kind in Type %}
			    <li><a href="{% url 'goods:type_list' kind.id  %}" class="{{ kind.logo }}">{{ kind.type }}</a></li>
                {% endfor %}

				</ul>
			</div>
{% endblock %}
{% block content %}
<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ good.type.type }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ good.img.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good.name }}</h3>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good.price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{ good.price }}元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<!-- <a href="javascript:;" class="buy_btn">立即购买</a> -->
				<a href="javascript:;" sku_id="{{ good.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for x in goods %}
					<li>
						<a href="{% url 'goods:goods' x.id %}"><img src="{{ x.img.url }}"></a>
						<h4><a href="{% url 'goods:goods' x.id %}">{{ x.name }}</a></h4>
						<div class="prize">￥{{ x.price }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li id='tag_detail' class="active">商品介绍</li>
				<li id="tag_comment">评论</li>
			</ul>

			<div class="tab_content" id="tab_detail">
				<dl>
					<dt>商品详情：</dt>
                    <dd><p><strong>{{ good.desc }}</strong></p></dd>
				</dl>
			</div>

            <div class="tab_content" id="tab_comment" style="display: none">
				<dl>

				</dl>
			</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


	<div class="add_jump"></div>



	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
        $('#tag_detail').click(function () {
            $('#tag_comment').removeClass('active')
            $(this).addClass('active')
            $('#tab_detail').show()
            $('#tab_comment').hide()
        })

        $('#tag_comment').click(function () {
            $('#tag_detail').removeClass('active')
            $(this).addClass('active')
            $('#tab_detail').hide()
            $('#tab_comment').show()
        })

        update_goods_amount()
        // 计算商品的总价格
        function update_goods_amount() {
            // 获取商品的单价和数量
            price = $('.show_pirze').children('em').text()
            count = $('.num_show').val()
            // 计算商品的总价
            price = parseFloat(price)
            count = parseInt(count)
            amount = price*count
            // 设置商品的总价
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        // 增加商品的数量
        $('.add').click(function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 加1
            count = parseInt(count)+1
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 减少商品的数量
        $('.minus').click(function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 减1
            count = parseInt(count)-1
            if (count <= 0){
                count = 1
            }
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 手动输入商品的数量
        $('.num_show').blur(function () {
            // 获取用户输入的数目
            count = $(this).val()
            // 校验count是否合法
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
                count = 1
            }
            // 重新设置商品的数目
            $(this).val(parseInt(count))
            // 更新商品的总价
            update_goods_amount()
        })

        // 获取add_cart div元素左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
            // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id') // attr prop
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count,'csrfmiddlewaretoken':csrf }
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('/cart/add', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
			        });
                }
                else{
                    // 添加失败
                    alert('请先登入')
                    location.href='/user/login?next=/goods/{{ good.id }}/'
                }
            })
		})
	</script>


{% endblock %}

apps/goods/templates/index.html
{% extends 'base.html' %}
{% block content %}

	<div class="center_con clearfix">
		<ul class="subnav fl">
                {% for kind in Type %}
			    <li><a href="#model0{{ kind.id }}" class="{{ kind.logo }}">{{ kind.type }}</a></li>
                {% endfor %}

		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                    {% for ban in banner %}
				    <li><a href="#"><img src="{{ ban.img.url }}" alt="幻灯片"></a></li>

                    {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
                {% for act in active %}
			    <a href="#"><img src="{{ act.images.url }}"></a>
                {% endfor %}
		</div>
	</div>

    {% for list in Type %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model{{ list.id }}">{{ list.type }}</h3>
			<a href="{% url 'goods:type_list' list.id %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ list.image.url }}"></div>
			<ul class="goods_list fl">
                {% for x in list.goods_set.all|slice:':4' %}
				<li>
					<h4><a href="{% url 'goods:goods' x.id %}">{{ x.name }}</a></h4>
					<a href="{% url 'goods:goods' x.id %}"><img src="{{ x.img.url }}"></a>
					<div class="prize">¥ {{ x.price }}</div>
				</li>

                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}




	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{% endblock %}

apps/goods/templates/search.html
{% extends 'base.html' %}
{% block nav %}
<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                   {% for kind in Type %}
			    <li><a href="{% url 'goods:type_list' kind.id  %}" class="{{ kind.logo }}">{{ kind.type }}</a></li>
                {% endfor %}

				</ul>
			</div>
{% endblock %}

{% block content %}
<div class="breadcrumb">
		<a href="#">{{ fruit }}</a>
		<span>></span>
		<a href="#">搜索结果如下:</a>
	</div>

	<div class="main_wrap clearfix">
        <ul class="goods_type_list clearfix">
            {% for x in page_obj %}
            <li>
                <a href="{% url 'goods:goods' x.id %}"><img src="{{ x.img.url }}"></a>
                <h4><a href="{% url 'goods:goods' x.id %}">{{ x.name }}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{ x.price }}</span>
                    <span class="unit">{{ x.price }}/500g</span>
                </div>
            </li>
            {% endfor %}


        </ul>
        <div class="pagenation">
            {% if page_obj.has_next %}
				        <a href="{% url 'goods:search' %}?fruit={{ fruit }}&page={{ page_obj.next_page_number }}" class="active">&gt</a>
            {% endif %}

			</div>




	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

apps/goods/templates/type_list.html
{% extends 'base.html' %}
{% block title %}
<title>天天生鲜-商品分类</title>
{% endblock %}
{% block jc %}
<style>
    .contain>div{
        float: left;
    }
    #left{
        width: 200px;
        height: 600px;
        margin-left: 100px;
    }
    #right{
        margin-left: 50px;

    }
ul>li{
    list-style: none;
}
p{
    text-align: center;
}
#right{
    margin-top: 60px;
    font-size: 20px;
    width: 1000px;

}
.top_con{
    background-color: #d6e9c6;
    height: 40px;
}
.top_con>a{
    margin-left: 20px;

}
.foot_con>ul>li{
    float: left;
    margin: 30px;
    border: 1px solid greenyellow;
    border-radius: 10px;
}
.page>ul>li{
    float: left;
    margin: 10px;
    height: 20px;
    width: 20px;
    border: 1px solid #bce8f1;
    text-align: center;

}
.page{
    margin-left: 500px;
    margin-top: 10px;
}
</style>
{% endblock %}
{% block nav %}
<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                   {% for kind in Type %}
			    <li><a href="{% url 'goods:type_list' kind.id  %}" class="{{ kind.logo }}">{{ kind.type }}</a></li>
                {% endfor %}

				</ul>
			</div>
{% endblock %}
{% block content %}
    <div class="contain">
<div id="left">
    <div style="font-size: 20px;margin-top: 10px;text-align: center;color: #00bc6f">全部分类 &gt {{ kinds.type }}</div>
    <div style="text-align: center;font-size: 20px;margin-top: 20px;background: greenyellow">新品推荐</div>
    <div>
        <ul>
            {% for ls in goods_list|slice:'0:2' %}
            <li>
                <a href="{% url 'goods:goods' ls.id %}"><img src="{{ ls.img.url }}"  style="width: 199.99px;height: 211.1px">
            <p>{{ ls.name }}</p>
            <p>￥ {{ ls.price }}</p>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="right">
    <div class="top_con">
        <a href="{{ request.path }}?order_by=id">默认</a>
        <a href="{{ request.path }}?order_by=price">价格</a>
    </div>
    <div class="foot_con">
    <ul>
            {% for obj in page_obj %}
            <li>
            <a href="{% url 'goods:goods' obj.id %}">
                <img src="{{ obj.img.url }}"  style="height: 235.31px;width: 181.98px">
                <p>{{ obj.name }}</p>
                <p>￥ {{ obj.price }}</p>
            </a>
            </li>

            {% endfor %}
        </ul>
    </div>

</div>
     <div class="page">
    <ul>
        {% if page_obj.has_previous %}
        <li><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&lt</a></li>
        {% endif %}
        {% for x in paginator %}
        <li style="{% if page_obj.number == x.number %} background-color: #dddddd {% endif %}"><a href="{{ request.path }}?page={{ x.number }}">{{ x.number }}</a> </li>
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">&gt</a></li>
    {% endif %}
    </ul>
</div>
    </div>
{% endblock %}